[package]
name = "stats_server"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = { version = "0.3.1", features = ["tls"] }
uuid = "0.8.2"
json = "0.12.4"
clap = "2.33.3"
colored = "2.0.0"
chrono = "0.4.19"